- hosts: all
  name: Configure EOS Interfaces
  gather_facts: false
  become: true
  vars:
    nb_api_endpoint: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    nb_api_token: "{{ lookup('ansible.builtin.env', 'NETBOX_API_TOKEN') }}"
    dev_l3_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='tag=l3base device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
    dev_ips: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                 api_endpoint=nb_api_endpoint,
                 api_filter='device=' ~ inventory_hostname, 
                 token=nb_api_token) }}"
  tasks:
    - name: Configure Interfaces as L3
      arista.eos.eos_interfaces: 
        config:
        - name: "{{ item.value.name }}"
          enabled: true
          mode: layer3
        state: merged
      loop: "{{ dev_l3_intfs }}"
      loop_control:
        label: "{{ item.value.name }}"
      
    - name: Configure IP Addresses
      arista.eos.eos_l3_interfaces:
        config:
          - name: "{{ item.value.assigned_object.name }}"
            ipv4:
            - address: "{{ item.value.address }}"
      loop: "{{ dev_ips }}"
      loop_control:
        label: "{{ inventory_hostname }}/{{ item.value.assigned_object.name }}"