- hosts: all
  name: Query Netbox Interfaces and IP Addresses
  gather_facts: false
  become: true
  vars:
    nb_api_endpoint: "{{ lookup('ansible.builtin.env', 'NETBOX_URL') }}"
    nb_api_token: "{{ lookup('ansible.builtin.env', 'NETBOX_API_TOKEN') }}"
    dev_intfs: "{{ query('netbox.netbox.nb_lookup', 'interfaces',
                      api_endpoint=nb_api_endpoint,
                      api_filter='cabled=True device=' ~ inventory_hostname,
                      token=nb_api_token) }}"
  tasks:
    - name: Display Hostname
      debug: 
        msg: "{{ inventory_hostname }}"
    - name: Output Interfaces
      debug: 
        msg: "{{ item.value.name }}"
      loop: "{{ dev_intfs }}"
      loop_control:
        label: "{{ item.value.name }}"
    - name: Output IP addresses
      debug:
        msg: "{{ query('netbox.netbox.nb_lookup', 'ip-addresses',
                 api_endpoint=nb_api_endpoint,
                 api_filter='device=' ~ inventory_hostname ~ ' interface=' ~ item.value.name,
                 token=nb_api_token) | json_query('[*].value.address | [0]')}}"
      loop: "{{ dev_intfs }}"
      loop_control:
        label: "{{ item.value.name }}"